CREATE TABLE inventory (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
item_name TEXT,
item_quantity INTEGER,
the_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE donor (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
f_name TEXT NOT NULL,
l_name TEXT,
phone_No TEXT NOT NULL
);

CREATE TABLE donation (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
item_name TEXT NOT NULL,
item_quantity INTEGER NOT NULL,
donation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
donor_id INTEGER,
FOREIGN KEY (donor_id) REFERENCES donor (id)
);

CREATE TABLE inventory_donation (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
inventory_id INTEGER,
donation_id INTEGER,
FOREIGN KEY (inventory_id) REFERENCES inventory (id),
FOREIGN KEY (donation_id) REFERENCES donation (id)
);

CREATE TABLE user (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT,
password TEXT,
role INTEGER DEFAULT 0
);




